spring:
  config:
    activate:
      on-profile: dev
  application:
    name: dangol-sonnim-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dangol-sonnim-backend-dev.cus5l7nkmcs0.ap-northeast-2.rds.amazonaws.com:3306/dangol_sonnim
    username: admin
    password: backend!

  jpa:
    hibernate:
      ddl-auto: update
      # hibernate가 db에 보내는 모든 쿼리문 보여줌
      show-sql: true
      # 보이는 query를 가독성 좋게 formatting
      format_sql: true
      # 추가적인 주석 표시하기
      use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    # Security OAuth
    security:
      oauth2.client:
        registration:
          google:
            clientId: '427373259154-sctrl0ape8bquj0ulb568lfpj4emmea4.apps.googleusercontent.com'
            clientSecret: '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'
            scope:
              - email
              - profile
          naver:
            clientId: 'ndmqD1jQYjFAbdrM3Z6O'
            clientSecret: 'y3P8gUvcPD'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "https://dangol.store/login/profile"
            scope:
              - email
              - profile_image
            clientName: Naver
          kakao:
            clientId: '213a6caa659b3805a4c617e8c9ae301d'
            clientSecret: 'ptxeVyTphmDQ0AnIVvJkkqzkC09YegVr'
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "https://dangol.store/login/profile"
            scope:
              - profile-image
              - account_email
            clientName: Kakao
        # Provider 설정
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: jaemisama12@gmail.com #앱 비밀번호 발급받은 google 계정
    password: xakhfxznsceodhni #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: "${port:8080}"

jwt:
  secret: "e11f1026efe6e2c908d386fc056d7057c607eac31cae8614abc64b35f9ea72b78564e1858f9d4cc8fea5c63ff2ec54618a409cb372fbed248c62d3d995112676"
  access-expiration-in-ms: 3600000
  refresh-expiration-in-ms: 1209600000
  refresh-header: Authorization-refresh
